# Generated by Django 2.2 on 2021-03-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210203_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(default='default.png', upload_to='banners'),
        ),
    ]
